### ISSUE TITLE
Why Redis?

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/redis#1]
Why did you choose to containerize Redis? Are you using it on some application?
If yes, then you should probably containerize that application too, in order to test Redis properly.
If no, then I would suggest to choose some other application for containerization.

And why did you choose **wsproxy** as an example? It is quite a complex application.
If you want to continue with Redis, I would suggest to use **mariadb** as an example, which is used by the application **dbox**.

**Comment by dashohoxha** [comment]
Are you reading the issues? Are you trying to close them?
Or you just prefer to do what you like and how you like it?

**Comment by RadZaeem** [comment]
Yes I read the issues.

Since currently there is no app that I use is using redis, I am considering to containerize other app instead. Is it okay.

**Comment by dashohoxha** [comment]
If you have some familiarity with Drupal7, you could modify **dbox** to use Redis:
 - https://2bits.com/articles/installing-configuring-redis-drupal-7-other-memcached-alternatives.html
 - https://redislabs.com/lp/drupal-redis/

Otherwise it is better to choose another application. Select an application that you use and you care about, because this will motivate you to make it properly.

**Comment by RadZaeem** [comment]
OK I will try to modify **dbox** so that it will use Redis container I made.
I will update you the code later.

**Comment by dashohoxha** [comment]
First, finish studying all the example applications. You have plenty of time, almost 10 days for doing this properly.

Second, try to make it optional, so that the **dbox** users can use the **redis** cache if they wish, but are not forced to use it.

**Comment by RadZaeem** [comment]
OK noted.

**Comment by RadZaeem** [comment]
I made a `dbox`-based container which uses Drupal Redis module that connects with with this `redis` container I made.
I tested it and confirmed it to be working.
https://github.com/RadZaeem/myproject/

**Comment by dashohoxha** [comment]
Create a PR on the `dbox` project with the changes that you made.

**Comment by RadZaeem** [comment]
I need permission to push my branch to the dbox project

**Comment by dashohoxha** [comment]
I gave access. Sorry for the inconvenience.
